- hosts: localhost
  gather_facts: no
  vars:
    mysql_login_host: "{{ lookup('env', 'mysql_login_host') }}"
    mysql_root_user: "{{ lookup('env', 'mysql_root_user') }}"
    mysql_root_password: "{{ lookup('env', 'mysql_root_password') }}"
    mysql_users:
      - { name: user1, state: present, host: 'localhost', priv: 'database_a.*:SELECT', password: password1 }
      - { name: user2, state: present, host: 'localhost', priv: 'database_a.*:SELECT/database_b.*:ALL', password: password2 }
      - { name: user3, state: present, host: 'localhost', priv: 'database_b.*:ALL', password: password3 }

  tasks:
    - name: Ensure MySQL is ready
      wait_for:
        host: mysql
        port: 3306
        delay: 10
        timeout: 30

    - name: Create MySQL users
      mysql_user:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
        host: '{{ item.host }}'
        priv: '{{ item.priv }}'
        password: '{{ item.password }}'
        login_host: '{{ mysql_login_host }}'
        login_user: '{{ mysql_root_user }}'
        login_password: '{{ mysql_root_password }}'
      loop: '{{ mysql_users }}'

    - name: Create databases
      mysql_db:
        name: "{{ item }}"
        state: present
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
      loop:
        - database_a
        - database_b

    - name: Echo MySQL users
      debug:
        var: mysql_users